### ISSUE TITLE
Stack exhaustion at 100k blocks

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/selfish#58]
maybe in BlockNext::amount

int BlockNext::amount(const string &user) const
{
        return parent->amount(user) + (user == miner ? 1 : 0);
}

Need to use tail recursion...

**Comment by DronMDF** [comment]
Yes, this is amount problem
```
#15326 0x000055555556316f in BlockNext::amount (this=0x555555b9b9f0, user="Alice") at /home/dron/Projects/selfish/BlockNext.cpp:63
#15327 0x000055555555dc0c in BlockCache::amount (this=0x555555b9bc10, user="Alice") at /home/dron/Projects/selfish/BlockCache.cpp:51
#15328 0x000055555556316f in BlockNext::amount (this=0x555555b9b8f0, user="Alice") at /home/dron/Projects/selfish/BlockNext.cpp:63
#15329 0x000055555555dc0c in BlockCache::amount (this=0x555555b9be40, user="Alice") at /home/dron/Projects/selfish/BlockCache.cpp:51
```
But problem is wider.
